throttle_to_wheelspeed: 3.0 # maximum desired car speed
model_path: "CORL_MPAIL_model_550.pt" # location of your model wieghts
model_type: "mlp" # mlp or cnn
steering_max: 0.488 # max steering angle in radians
rate: 50 # control frequency of the policy
obs_type: "blind" # the type of observation that must be passed in to the model
hidden_shape: [64, 64] # shape of hidden layers