[package]

# Semantic Versioning is used: https://semver.org/
version = "0.1.0"

# Description
category = "Algorithms"
readme  = "docs/README.md"

title = "MPAIL"
author = "Wheeled Lab Project Developers"
maintainer = "Wheeled Lab Project Developers"
description= "Model Predictive Adversarial Imitation Learning"
repository = "https://github.com/UWRobotLearning/WheeledLab-research.git"
keywords = []

[dependencies]
# NOTE: Add additional dependencies here

[[python.module]]
name = "mpail"

[isaaclab_settings]
# TODO: Uncomment and list any apt dependencies here.
#       If none, leave it commented out.
# apt_deps = ["example_package"]
# TODO: Uncomment and provide path to a ros_ws
#       with rosdeps to be installed. If none,
#       leave it commented out.
# ros_ws = "path/from/extension_root/to/ros_ws"